CREATE DATABASE dhphoto CHARACTER SET utf8;

USE dhphoto;

CREATE TABLE IF NOT EXISTS tbl_file_content(
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(70) NOT NULL,
  type VARCHAR(50) NOT NULL,
  size INT(11) NOT NULL,
  path VARCHAR(255) DEFAULT NULL,
  height INT(4) NOT NULL,
  width INT(4) NOT NULL,
  content MEDIUMBLOB DEFAULT NULL,
  extension VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 101
AVG_ROW_LENGTH = 8495
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE DATABASE dhdrivinglicence CHARACTER SET utf8;

USE dhdrivinglicence;

CREATE TABLE IF NOT EXISTS tbl_file_content(
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(70) NOT NULL,
  type VARCHAR(50) NOT NULL,
  size INT(11) NOT NULL,
  path VARCHAR(255) DEFAULT NULL,
  height INT(4) NOT NULL,
  width INT(4) NOT NULL,
  content MEDIUMBLOB DEFAULT NULL,
  extension VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 101
AVG_ROW_LENGTH = 8495
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE DATABASE dhidentification CHARACTER SET utf8;

USE dhidentification;

CREATE TABLE IF NOT EXISTS tbl_file_content(
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(70) NOT NULL,
  type VARCHAR(50) NOT NULL,
  size INT(11) NOT NULL,
  path VARCHAR(255) DEFAULT NULL,
  height INT(4) NOT NULL,
  width INT(4) NOT NULL,
  content MEDIUMBLOB DEFAULT NULL,
  extension VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 101
AVG_ROW_LENGTH = 8495
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE DATABASE dhdiploma CHARACTER SET utf8;

USE dhdiploma;

CREATE TABLE IF NOT EXISTS tbl_file_content(
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(70) NOT NULL,
  type VARCHAR(50) NOT NULL,
  size INT(11) NOT NULL,
  path VARCHAR(255) DEFAULT NULL,
  height INT(4) NOT NULL,
  width INT(4) NOT NULL,
  content MEDIUMBLOB DEFAULT NULL,
  extension VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 101
AVG_ROW_LENGTH = 8495
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE DATABASE dhcriminal CHARACTER SET utf8;

USE dhcriminal;

CREATE TABLE IF NOT EXISTS tbl_file_content(
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(70) NOT NULL,
  type VARCHAR(50) NOT NULL,
  size INT(11) NOT NULL,
  path VARCHAR(255) DEFAULT NULL,
  height INT(4) NOT NULL,
  width INT(4) NOT NULL,
  content MEDIUMBLOB DEFAULT NULL,
  extension VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 101
AVG_ROW_LENGTH = 8495
CHARACTER SET utf8
COLLATE utf8_unicode_ci;