-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07/11/2013 10:40:42
-- Server version: 5.5.8
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE directhomecare;

-- 
-- Dumping data for table tbl_carer_condition
--
INSERT INTO tbl_carer_condition VALUES 
  (548, 11),
  (549, 11),
  (550, 11),
  (552, 11),
  (557, 11),
  (558, 11),
  (559, 11),
  (560, 11),
  (548, 12),
  (557, 12),
  (558, 12),
  (559, 12),
  (560, 12),
  (548, 13),
  (557, 13),
  (558, 13),
  (559, 13),
  (560, 13),
  (548, 14),
  (557, 14),
  (558, 14),
  (559, 14),
  (560, 14),
  (548, 15),
  (557, 15),
  (558, 15),
  (559, 15),
  (560, 15),
  (548, 16),
  (557, 16),
  (558, 16),
  (559, 16),
  (560, 16),
  (548, 17),
  (557, 17),
  (558, 17),
  (559, 17),
  (560, 17),
  (548, 18),
  (557, 18),
  (558, 18),
  (559, 18),
  (560, 18),
  (548, 19),
  (557, 19),
  (558, 19),
  (559, 19),
  (560, 19),
  (548, 20),
  (557, 20),
  (558, 20),
  (559, 20),
  (560, 20),
  (548, 21),
  (549, 21),
  (550, 21),
  (557, 21),
  (558, 21),
  (559, 21),
  (560, 21);

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;