-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/05/2013 23:55:23
-- Server version: 5.5.8
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE directhomecare;

-- 
-- Dumping data for table tbl_carer_document
--
INSERT INTO tbl_carer_document(id, id_document, id_carer, status, active, year_obtained, id_content, id_content_crop, `text`, reject_reason) VALUES 
  (257, 59, 559, 1, 0, NULL, NULL, NULL, 'Per.', ''),
  (258, 58, 559, 1, 0, NULL, NULL, NULL, 'Mot.', ''),
  (259, 3, 559, 1, 0, NULL, 740, 741, NULL, NULL);

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;